/-! 
# Do a bunch of commutative algebra for this week
and graph theory next week

Or can ask questions instead

And gonna talk about universes too

Picard groups:

Input is a commutative ring R
Output is an abellian group Pic(R)

Know two construction
## Construction 1

Let X = set of all ideals of R
if I, J ▵ R are ideals,
then we can define I + J and I ⨯ J

I + J = {i+j | i ∈ I, j ∈ J}
I ⨯ J ≠ {i⨯j | i ∈ I, j ∈ J} as this might not be an ideal,
Define I ⨯ J be the ideal generated by {i⨯j | i ∈ I, j ∈ J}

### Note, this is a group without an inverse, called a monoid

1 ∈ X := R (unit ideal)
I ⨯ 1 = 1 ⨯ I = I
and
(IJ)K = I(JK)

#### Interlude

Let G a group.
Q1) What are the subobjects of G, i.e. injective group homs X → G?
    These are basically the subgroups of G
Q2) What are all the quotient objects of G, i.e. surjective group homs G → Y
    The 1st iso theorem Y ≅ G/ker(φ), so Y is determined by kerφ a normal subgroup
    Conversily if N (normal triangle) G
    G → G⧸N is a quotient

Monoids are "horrible"
  A = {0,1,2} under addition
  Define
  x+y = 2 if actual x+y ≥ 2

Similarly B = {0,1,2,3}

And there exists a monoid hom from B to A
Quotient not by subobjcets but equivalence relations!

-----------------------------------------
Warning cannot use a random equivalence relation,
as one one want G a monoid which has N : equivalence relation on G

G/N ~~equiv class~~ / quotient

Want multiplication to decend!

G   ⨯  G   →    G
|      |        |
↓      ↓        ↓
G⧸N ⨯  G⧸N - - → G⧸N

Ideals of R is a monoid

equiv I ~ J ↔ I ≅ J as an R-module (R-vector space)

≅ is weaker than equality (take 2 different 1d sub vector spaces, they span the same thing)

Q) Is "≅" a congruance relation?
Yes.

Conclusion X⧸≅ is a quotient monoid

If R ≠ {0} then is not a group!

n ⨯ n Matrix over the complex under X,
take units = GLₙ(ℂ) = invertible matrices 
= group,  R⨯ (units of R)

#### End of interlude

Picard group of R = Unit group of (ideals of R)⧸(equivalences)

Define an 

## Kevin defining Picard group via Idels in Lean

## Or not, talking about universes now

## Construction 2
Picard groups via R modules

Let R be a commutative ring
If V, W are R-modules, then there is a consecpt of being isomorphic
V ≅ᵣ W
Product on R modules its the tensor product

V ⊗ W another R module
not V ⨯ W, its usually bigger

Typicial element of this tensor product is 

V₁ ⊗ W₁ + V₂ ⊗ W₂

Is ⊗ associative?
(I×J)×K = I×(J×K) equality of type ideal R

Is V⊗ᵣ(W⊗ᵣX) = (V⊗ᵣW)⊗ᵣX ?
is an equality of *types*

But V⊗ᵣ(W⊗ᵣX) ≅ (V⊗ᵣW)⊗ᵣX is true

Modules over R have some "quasi-multiplication"
  ⊗ exist but R ⊗ V ≠ V and R ⊗ V ≅ V

Let M =  all R=modules,

equiv relation on M ≅ Picard group

### Doing it in Lean in section13 again now

congr lemmas are a useful thing to know
linear_equiv probaly too

##### To get ⊗ notation
open_locale tensor_product

-/

